### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by wjx0912** [puux/iptables#3]
hi, puux,
thanks for you work, it's useful for me. but have a problem,
when i start a terminal, and run "node ./server.js", all works well, 
but if i add 
/usr/local/bin/node /root/iptables/server.js
at end of /etc/rc.local  (debian9), the login web show '404 error'.
does it's a bug?

thanks

**Comment by puux** [comment]
hi, wjx0912

No, it's not a bug. The application requires the specified working directory. Try this:
cd /root/iptables/ && /usr/local/bin/node server.js

**Comment by wjx0912** [comment]
it works, thank you.
